[[redirects]]
  from = "/"
  to = "https://heritage-hub-eg.vercel.app/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://heritage-hub-eg.vercel.app/:splat"
  status = 301
  force = true